image: node:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - dependencies
  - build
  # - test
  - quality

cache:
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  script:
    - npm install
    - npm install standard mocha istanbul
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  
# test:
  # stage: test
  # script:
    # - npm test

quality:
  stage: quality
  script:
    - ./node_modules/.bin/istanbul cover _mocha
